
import { getDictionary } from './dictionaries'
import { MetadataRoute } from 'next/server'
// import { useRouter } from 'next/navigation'
import {Button} from '@nextui-org/button'; 


export default async function Page({ params}) {
    const { lang } = await params
  const dict =  await getDictionary(lang)
  // const router = useRouter();

  return (
    <div>
      <h1>{dict.greeting}</h1>
      <p>This is the movies page, locale: {lang}</p>
      {/* <button onClick={() => router.push(router.asPath.replace(`/${router.locale}`, `/en`), undefined, { locale: "en" })}>Go to English</button> */}


    </div>


  );
}


  export const metadata = {
    title: 'My movie site',
    description: 'Generated by create next app',
  }


  